### ISSUE TITLE
Usage of CRON functions in theme

### ISSUE THREAD

**Issue by dingo-d** [WPTRT/WPThemeReview#146]
We were going through the upstream sniffs during the meeting, especially through [CronIntervalSniff](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/WP/CronIntervalSniff.php), and we don't know whether to use it or not, because we don't have an agreement if we should allow cron jobs inside themes at all.

So a discussion is needed on this prefferably in the WPTRT meeting.

**Comment by justintadlock** [comment]
Cron jobs are plugin territory and not currently allowed in themes.

**Comment by grappler** [comment]
> As in, a sniff which checks for cron jobs being added/altered/removed ?

Yes, I think that would make sense as theme should not be running regular tasks.

**Comment by justintadlock** [comment]
Team discussed this.  Can this be combined with an existing sniff for disallowed functions?  If that's the best route, take it.  Otherwise, implement a specific sniff for this.

Meeting: https://wordpress.slack.com/archives/C02RP4Y3K/p1528822802001090

**Comment by jrfnl** [comment]
Thanks for the update. There will be one or more sniffs which will disallow functions, this is not included yet, but being worked on. If all that needs forbidding is functions, this will be included when I pull it.

Are there any cron hooks which should be forbidden too ?

**Comment by dingo-d** [comment]
We didn't mention specific hooks, but in general, all cron meddling in the theme should be forbidden.

**Comment by dingo-d** [comment]
Should this be in the `ForbiddenFunctionsSniff` or should I create a new sniff `DisallowCRONUsageSniff` ? Because it seems to me like cron is a plugin territory, and if this is correct, I can add those to the #215 PR 🙂

**Comment by dingo-d** [comment]
This has been merged in the `develop` branch and will be released with 0.2.0.
