### ISSUE TITLE
Proposal: change ruleset and repo name

### ISSUE THREAD

**Issue by jrfnl** [WPTRT/WPThemeReview#167]
As this repo was (is) a fork from WPCS, when this project started, it was decided to create a `WordPress-Theme` ruleset in line with existing rulesets in WPCS.

However, things change. And one of the things which is about to change is that the repo will be de-forked from WPCS.

This means that, from that point onwards, the TRTCS can choose its own standard name and have additional rulesets too.

## Proposal 1: Change the standard name

The standard is currently called `WordPress-Theme`.

When the repo is de-forked and PHPCS 3.x will be the minimum supported PHPCS version, all sniffs will need to be in a PHP namespace. While, with a work-around, a different namespace can be used, the default PHPCS supported behaviour is to have the standard name as the namespace name.

Dashes `-` aren't allowed as a character in namespaces, so we need to make a choice of what to do:
1. Keep the `WordPress-Theme` name and use the work-around for the namespace. The namespace could then, for instance, be `WPTheme`.
2. Change the standard name to `WPTheme` and have the namespace be in sync with that.

I would like to propose option 2 for this for the following reasons:
* Support for work-arounds may not be guaranteed in the future.
* Staying close to the default supported behaviour in PHPCS seems sensible.
* Changing the name will make the de-forking more obvious and make a clearer distinction between this repo and WPCS.

:point_right: Opinions welcome.

## Proposal 2: What name to use ?

In the above proposal, I suggest `WPTheme`, but any sensible name which complies with the PHP namespace name limitations could be used.

Ideas/Suggestions:
* `WPTheme`
* `WPThemeCS`
* `WPTRTCS`

:point_right: Alternative ideas welcome. Comments voting for any of these names too.

## Proposal 3: Rename the repo

As this repo will no longer be a fork of WPCS, keeping the name `WordPress-Coding-Standards` is misleading and will cause confusion.

I propose to rename the de-forked repo to whatever is decided the standard name will become.

GH has a build-in redirection mechanism, so people used to the old name, should be redirected to the renamed repo without problems.

I'm not sure whether this repo is on Packagist yet. If so, the Packagist reference may need to be adjusted as well.

:point_right: Opinions welcome.

**Comment by dingo-d** [comment]
In general, people are ok with `WPTheme`. A proposal by @joyously was `WPThemeReview` which doesn't sound bad. And would look ok for a repository name. Also she mentioned that `WPTheme` could be mistaken for WP core themes (Twenty*).

There weren't many people on the meeting so not too much opinion about this.

I also like `WPThemeReview` 🙂

**Comment by dingo-d** [comment]
We've agreed on the name, and it should be `WPThemeReview`.

**Comment by jrfnl** [comment]
The repo has been detached from WPCS, so I've gone ahead and changed the repository name.

The ruleset name will change in the PR which will address the code-wise detaching from WPCS.

**Comment by dingo-d** [comment]
This issue can be closed since we have detached from the WPCS and added `WPThemeReview` as the name. Or do you want to wait for when we get the categories and you make the separation?

**Comment by jrfnl** [comment]
@dingo-d Only the repo name has changed so far (Proposal 3). The change has not been made in the code yet - well, it has, but only on my local machine - (Proposal 1). Once that's sorted the issue can be closed.

**Comment by dingo-d** [comment]
:+1: Thanks for the clarification

**Comment by jrfnl** [comment]
As the repo history has now been rewritten and the change is contained in the `develop` and `master` branch, I'm closing this issue.
