### ISSUE TITLE
Referenced sniff "WordPress.CodeAnalysis.EmptyPHPStatement" does not exist

### ISSUE THREAD

**Issue by ntwb** [WPTRT/WPThemeReview#185]
Once up and running `./vendor/bin/phpcs -p . --standard=WPThemeReview` results in:

> `ERROR: Referenced sniff "WordPress.CodeAnalysis.EmptyPHPStatement" does not exist`

Removing the following works around the issue:
>https://github.com/WPTRT/WPThemeReview/blob/50ba5f783d4848342fc82760fa2211a0a9697eff/WPThemeReview/ruleset.xml#L51-L52

My `composer.json` contents:
```json
	"require-dev": {
		"dealerdirect/phpcodesniffer-composer-installer": "~0.4.4",
		"wp-coding-standards/wpcs": "~1.1.0",
		"wptrt/wpthemereview": "dev-develop"
	},
```

**Comment by jrfnl** [comment]
You're right, PR upcoming.

**Comment by dingo-d** [comment]
The PR has been merged, @ntwb can you please test it now, just to be on the safe side? 🙂
