### ISSUE TITLE
🍾 Next release planning [0.2.0]

### ISSUE THREAD

**Issue by dingo-d** [WPTRT/WPThemeReview#189]
Now that the 0.1.0 is out 🎉 I think that we should try to keep the momentum and make some kind of planning as to what can be done for the next release 🙂 

We can have a hangouts meeting, but we can also leave comments here about it.

I was thinking that we should go through the issues, see what can be closed, and maybe see which sniff proposals would be good to tackle (maybe some easy ones).

Even setting up a release timeline wouldn't be a bad idea, maybe set a milestone (or even several of them) and go through the issues and tag them according to each milestone. This will give us some sense of completion for each release.

I'd also like for theme review admins to join so that we can update the theme review handbook, to closely follow the standards (for less confusion), but also because it could do with some updates in the general sense 🙂 

And last but not the least, we need to find a way to reach out to find more contributors. This part is the trickiest, but people need to know that contributing is not only writing sniffs but also writing good/bad code examples.

I'd like to hear your thoughts about this.

@jrfnl @grappler @ernilambar @jocastaneda @carolinan @justintadlock @pattonwebz

**Comment by joyously** [comment]
Does that include making it so anyone can run it? My eyes glaze over if I have to install 3 tools to use this tool.

**Comment by dingo-d** [comment]
It's actually super easy to run it in a project, you can check the twentynineteen and [wprig PR](https://github.com/wprig/wprig/pull/156), it's a matter of adding it to composer and running the composer script. Couldn't be easier 😄

**Comment by dingo-d** [comment]
> Well, yes it's easier if I don't have to figure out Composer and its script. I like the WP plugin route.

This is where theme-sniffer comes into play, but that's not related to this repo 😉

**Comment by dingo-d** [comment]
Just a self reminder: Downgrade the prefix sniff to a warning instead of error in the next release, and possibly release the `0.2.0` (or `0.1.1`) this week so that it can be used in the next release of the Theme Sniffer plugin

**Comment by jrfnl** [comment]
> Downgrade the prefix sniff to a warning instead of error in the next release, 

I would strongly recommend against that. If anything, you may just want to downgrade the specific message about non-prefixed variables which is causing all the strive, definitely not the whole sniff.

> possibly release the 0.2.0 (or 0.1.1) this week so that it can be used in the next release of the Theme Sniffer plugin

I'd suggest holding off for a week or so, WPCS 2.1.0 is expected to be released soon and it might be a good idea to update before releasing a new Theme Sniffer version.

**Comment by dingo-d** [comment]
The progress of the 0.2.0 release is as follows:

### Added

* Added modified PrefixAllGlobals sniff (PR #208)

### Changed

* Updated WPCS to 2.1.0 version (PR #211)
* Updated TravisCI against different mixes of PHPCS and WPCS versions (PR #210)
* Updated NoAddAdminPagesSniff (PR #206)
* Updated ruleset grammar changes (PR #204)
* Updated TravisCI builds against PHP 7.4 and workaround for PHPUnit 8 (PR #198)
* Updated composer-installer package to 0.5.0 version (PR #197)
* Updated readme (PR #195)

### Removed

* Removed autoload.php used in tests (PR #196)


## To do (PRs pending review):

* Review URL shorteners sniff (PR #216)
* Review adding additional functions to forbidden functions sniff (PR #215) - comment in issue #146 
 - decision needed to include CRON functions in the list or to create a new sniff
* Review required template functions sniff (PR #214)
* Review reserved template name sniff (PR #213)

* Issue grooming

**Comment by jrfnl** [comment]
One more TODO: I expect WPCS 2.1.1 to be released this week, so TRTCS may as well upgrade to using that (should be automatic as there is no `composer.lock`, but being explicit doesn't hurt).

**Comment by dingo-d** [comment]
All the changes will be in the [changelog](https://github.com/WPTRT/WPThemeReview/blob/develop/CHANGELOG.md) once the release is out, I'll close this issue and when the release is out and I sit down a bit I will open a new roadmap for the next release.
