### ISSUE TITLE
Allow two new tags in style.css

### ISSUE THREAD

**Issue by joyously** [WPTRT/WPThemeReview#192]
Two new tags added in https://meta.trac.wordpress.org/ticket/3921
They need to be allowed in style.css Tags.

**Comment by dingo-d** [comment]
Not sure we have tags list in the phpcs standards, but it will be useful for [Theme Sniffer](https://github.com/WPTRT/theme-sniffer/blob/master/inc/helpers.php)

**Comment by dingo-d** [comment]
The tags are pulled from API in Theme Sniffer when we release the `WPThemeReview` v 0.2.0, if not already in, this should be in the newest release of the Theme Sniffer plugin.
