### ISSUE TITLE
False positive on loading stylesheet in JS file

### ISSUE THREAD

**Issue by joyously** [WPTRT/WPThemeReview#202]
Two examples of jQuery code  that produce an error for `Stylesheets must be registered/enqueued via wp_enqueue_style`

`$('link[rel="stylesheet"]:not([data-inprogress])').forEach(StyleFix.link);`
and
`$('link[rel="stylesheet"]').forEach(StyleFix.link);`

**Comment by jrfnl** [comment]
This is not an issue with the TRTCS sniffs, but a WPCS issue. It is a valid bug though.

I've send in a PR to fix this to WPCS - see https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/1644.

Once the PR is merged, WPCS has released a new version and TRTCS has updated the WPCS dependency to this new version, this bug will be fixed for TRTCS as well.

**Comment by jrfnl** [comment]
The fix was merged a while ago and will be included in the WPCS 2.1.0 release which is expected soon.

**Comment by dingo-d** [comment]
The `WPCS 2.1.0`is out, and the `0.2.0` version will have this included, so is it's safe to close this issue @jrfnl ?

**Comment by jrfnl** [comment]
Yes, I believe it is.
