### ISSUE TITLE
Dealing with rules that shouldn't apply to templates

### ISSUE THREAD

**Issue by justintadlock** [WPTRT/WPThemeReview#205]
Some of the sniffs that we have should not apply to theme templates.  This is simply because the nature of the template system is different than other PHP in a theme.

Below are a couple of existing tickets where it's been noted that sniffs are either not necessary or provide a false-positive in the context of a template.

- https://github.com/WPTRT/WPThemeReview/issues/200
- https://github.com/WPTRT/WPThemeReview/pull/204

This is a general, catchall ticket to discuss ideas about dealing with this issue.

**Comment by dingo-d** [comment]
I think we can close this one as wee, as we've merged the updated prefix check sniff, and the reserved template names should be merged in 0.2.0.
