### ISSUE TITLE
twentyseventeen theme: posts with no date - but date is shown in similar posts

### ISSUE THREAD

**Issue by homebeaver** [WPTRT/WPThemeReview#263]
Hi, 

I use twentyseventeen theme in my blog. And I decided not to show dates in my posts:

![grafik](https://user-images.githubusercontent.com/3493126/117220613-da92f400-ae07-11eb-8107-588bcc59ebc4.png)

This works.

But the Block "similar Posts" shows the dates:

![grafik](https://user-images.githubusercontent.com/3493126/117220850-58ef9600-ae08-11eb-88dc-32a011fa10c6.png)

I did not find any option not to show this. In my opinion it is an inconsistency.
Do anyone have a hint to resolve this,

Regards EUGen

**Comment by dingo-d** [comment]
Hi, you should use https://wordpress.org/support/ for these kind of questions. This has nothing to do with theme coding standards.
