### ISSUE TITLE
Check for Author URI and Theme URI

### ISSUE THREAD

**Issue by khacoder** [WPTRT/WPThemeReview#49]
[New sniff] Check for Author URI and Theme URI
#### Rule type:

Warning
#### Rule:

WARNING | Check specifically against style.css whether the two recommended headers are found.

> Rule as it is found in the handbook.
> There is no specific rule in the handbook for this.
#### Theme check file covering this rule:

https://github.com/Otto42/theme-check/blob/master/checks/style_suggested.php
#### [Optional Section] Decision needed:

Stylesheets and Scripts (Recommended)
The main style.css header can optionally include Author URI and Theme URI.

**_Advice/Request for decision_**: Should the above header recommendation be added to the recommended list?
##### Notes for implementation:
- This sniff will rely on the WordPress_AbstractThemeSniff Class to get the $sniff_helper array.
- Testing will require that a style.css file is in the same folder as the test file.
#### To do:
- [ ] Decision/Add the rule in the Theme Review handbook to the **_Recommended_** page.
- [ ] Create unit tests
- [ ] Create new sniff
- [ ] Adjust existing WPCS / PHPCS sniff and send in PR upstream.
- [ ] Add existing `sniffname` sniff to the ruleset.

**Comment by khacoder** [comment]
I have this sniff ready to go, however it uses the $sniff_helper array from the proposed WordPress_AbstractThemeSniff class.

**Comment by dingo-d** [comment]
This is checked in Theme Sniffer, there we have more lenience about actually doing an API call so I'll close this for now, as I don't think a sniff is a good candidate for this.
