### ISSUE TITLE
Check that all required headers in style.css are there.

### ISSUE THREAD

**Issue by khacoder** [WPTRT/WPThemeReview#50]
[New sniff] Check that all required headers in style.css are there.
#### Rule type:

Error
#### Rule:

ERROR | Check specifically against style.css whether the required headers are found. See Theme-Check plugin - /checks/style_needed.php for the list.

> Rule as it is found in the handbook.
> There are no other specific rules in this sniff. Most are pretty obvious.
#### Theme check file covering this rule:

https://github.com/Otto42/theme-check/blob/master/checks/style_needed.php
Required styles are also included in this theme check but they will have to be moved to a separate sniff.
#### [Optional Section] Decision needed:

There is only the one rule covering text domain requirements. The other checks that will be done are pretty obvious. However if we are striving for rule/sniff consistency I would suggest the following additions.
Stylesheets and Scripts (Required)
The main style.css header requires: Theme name, Description, Author, Version, License, License URI, and Text Domain.

**_Advice/Request for decision_**: Should the above header requirements be added to the requirements lists?
##### Notes for implementation:
- This sniff will rely on the WordPress_AbstractThemeSniff Class to get the $sniff_helper array.
- Testing will require that a style.css file is in the same folder as the test file.
#### To do:
- [ ] Decision and implementation  to add the rule in the Theme Review handbook to the **_Requirements_** page.
- [ ] Create unit tests
- [ ] Create new sniff
- [ ] Adjust existing WPCS / PHPCS sniff and send in PR upstream.
- [ ] Add existing `sniffname` sniff to the ruleset.

**Comment by khacoder** [comment]
I have this sniff ready to go, however it uses the $sniff_helper array from the proposed WordPress_AbstractThemeSniff class.

**Comment by dingo-d** [comment]
Again, I think this is something that is added in Theme Sniffer. Not sure if a sniff is needed for this 🤷‍♂ 

@timelsass comments?

**Comment by dingo-d** [comment]
We agreed to add this to the Theme Sniffer, because PHPCS 4 won't check css, so we'd have to deprecate this one.
