### ISSUE TITLE
Check for unapproved and deprecated tags in style.css.

### ISSUE THREAD

**Issue by khacoder** [WPTRT/WPThemeReview#52]
[New sniff] Check for unapproved and deprecated tags in style.css.
#### Rule type:

Error - unapproved
Warning - deprecated
#### Rule:

ERROR Theme tags in style.css must be approved theme tags.
WARNING Deprecated theme tags found in style.css.

> Rule as it is found in the handbook.
> Core Functionality and Features
> The theme tags in style.css and description must match the what the theme actually does in respect to functionality and design.
> This rule is a reasonable fit for the sniff. There are no other rules I can find.
> Ref: https://make.wordpress.org/themes/handbook/review/required/#core-functionality-and-features
#### Theme check file covering this rule:

https://github.com/Otto42/theme-check/blob/master/checks/style_tags.php
##### Notes for implementation:
- This sniff will rely on the WordPress_AbstractThemeSniff Class to get the $sniff_helper array.
- Testing will require that a style.css file is in the same folder as the test file.
#### To do:
- [ ] Create unit tests
- [ ] Create new sniff
- [ ] Adjust existing WPCS / PHPCS sniff and send in PR upstream.
- [ ] Add existing `sniffname` sniff to the ruleset.

**Comment by khacoder** [comment]
I have this sniff ready to go, however it uses the $sniff_helper array from the proposed WordPress_AbstractThemeSniff class.

**Comment by khacoder** [comment]
I would like to consolodate some sniffs into this one

Issue #24 PR 54 Accessibility sniff
Issue #47 PR 56 Theme Support Tags

I would also add the following :
- threaded-comments tag check
- editor-style tag check

Other checks to consider :
- layout checks - no columns selected warnings
- subject checks-no subjects or all subject warnings
- RTL-language-support check
- theme-options check

**Comment by dingo-d** [comment]
I'd leave this check to Theme Sniffer, as there we're pulling the tags from the API, while in sniff form, we'd have to manually track if the tag list has been updated or not. 
If a PR gets made about this, I won't be mad, but I think this can be closed for now 🙂
