### ISSUE TITLE
Check for deprecated function args

### ISSUE THREAD

**Issue by khacoder** [WPTRT/WPThemeReview#72]
[New sniff] Check for deprecated function arguments and issue Error if found.
#### Rule type:

Error
#### Rule:

> Use WordPress functionality and features first, if available.
> Use *_url() template tags, rather than bloginfo() equivalents.

Ref: https://make.wordpress.org/themes/handbook/review/required/#core-functionality-and-features

ERROR | Check for usage of deprecated WP functions and provide alternative based on the parameter passed. For details, see Theme-Check plugin - /checks/more_deprecated.php We could probably extend an existing sniff of similar ilk for this or even combine this with the other deprecated checks.
#### Theme check file covering this rule:

https://github.com/Otto42/theme-check/blob/master/checks/more_deprecated.php
#### To do:
- [ ] Create unit tests
- [ ] Create new sniff
- [ ] Adjust existing WPCS / PHPCS sniff and send in PR upstream.
- [ ] Add existing `sniffname` sniff to the ruleset.

**Comment by khacoder** [comment]
I have this sniff ready to go and will upload after final testing.

**Comment by grappler** [comment]
It has not been fully fixed

**Comment by dingo-d** [comment]
This has a PR #217 🙂

**Comment by dingo-d** [comment]
Merged to `develop` and will be released with 0.2.0 version 🙂
